interface ZIF_CDS_I_BKLOG_AREA_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZCDS_I_BKLOG_AREA,
 CREATE_ZCDS_I_BKLOG_AREA       TYPE /BOBF/ACT_KEY VALUE '506B8D4A64A21EDD8BF2CB6D3750874F',
 DELETE_ZCDS_I_BKLOG_AREA       TYPE /BOBF/ACT_KEY VALUE '506B8D4A64A21EDD8BF2CB6D3751074F',
 LOCK_ZCDS_I_BKLOG_AREA         TYPE /BOBF/ACT_KEY VALUE '506B8D4A64A21EDD8BF2CB6D374FC74F',
 SAVE_ZCDS_I_BKLOG_AREA         TYPE /BOBF/ACT_KEY VALUE '506B8D4A64A21EDD8BF2CB6D3751874F',
 UNLOCK_ZCDS_I_BKLOG_AREA       TYPE /BOBF/ACT_KEY VALUE '506B8D4A64A21EDD8BF2CB6D3750074F',
 UPDATE_ZCDS_I_BKLOG_AREA       TYPE /BOBF/ACT_KEY VALUE '506B8D4A64A21EDD8BF2CB6D3750C74F',
 VALIDATE_ZCDS_I_BKLOG_AREA     TYPE /BOBF/ACT_KEY VALUE '506B8D4A64A21EDD8BF2CB6D3751474F',
      END OF ZCDS_I_BKLOG_AREA,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZCDS_I_BKLOG_AREA,
        BEGIN OF LOCK_ZCDS_I_BKLOG_AREA,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZCDS_I_BKLOG_AREA,
        BEGIN OF UNLOCK_ZCDS_I_BKLOG_AREA,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZCDS_I_BKLOG_AREA,
      END OF ZCDS_I_BKLOG_AREA,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZCDS_I_BKLOG_AREA,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '506B8D4A64A21EDD8BF2CB6D374FA74F',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '506B8D4A64A21EDD8BF2CB6D374F674F',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '506B8D4A64A21EDD8BF2CB6D3750674F',
      END OF ZCDS_I_BKLOG_AREA,
      BEGIN OF ZCDS_I_BKLOG_AREA_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '506B8D4A64A21EDD8BF2CB6D3751E74F',
      END OF ZCDS_I_BKLOG_AREA_LOCK,
      BEGIN OF ZCDS_I_BKLOG_AREA_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '506B8D4A64A21EDD8BF2CB6D3751C74F',
      END OF ZCDS_I_BKLOG_AREA_MESSAGE,
      BEGIN OF ZCDS_I_BKLOG_AREA_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '506B8D4A64A21EDD8BF2CB6D3752074F',
      END OF ZCDS_I_BKLOG_AREA_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZCDS_I_BKLOG_AREA,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZCDS_I_BKLOG_AREA,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '506B8D4A64A21EDD8BF2CB6D374EC74F' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZCDS_I_BKLOG_AREA' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZCDS_I_BKLOG_AREA,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '506B8D4A64A21EDD8BF2CB8FB3A0C74F',
 ADMINISTRATIVE_DATA            TYPE /BOBF/DET_KEY VALUE '506B8D4A64A21EDD8BF2CB8FB3A0E74F',
      END OF ZCDS_I_BKLOG_AREA,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZCDS_I_BKLOG_AREA              TYPE /BOBF/OBM_NODE_KEY VALUE '506B8D4A64A21EDD8BF2CB6D374F074F',
 ZCDS_I_BKLOG_AREA_LOCK         TYPE /BOBF/OBM_NODE_KEY VALUE '506B8D4A64A21EDD8BF2CB6D374F874F',
 ZCDS_I_BKLOG_AREA_MESSAGE      TYPE /BOBF/OBM_NODE_KEY VALUE '506B8D4A64A21EDD8BF2CB6D374F474F',
 ZCDS_I_BKLOG_AREA_PROPERTY     TYPE /BOBF/OBM_NODE_KEY VALUE '506B8D4A64A21EDD8BF2CB6D3750474F',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZCDS_I_BKLOG_AREA,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  AREA_ID                        TYPE STRING VALUE 'AREA_ID',
  AREA_DESC                      TYPE STRING VALUE 'AREA_DESC',
  ERNAM                          TYPE STRING VALUE 'ERNAM',
  ERDAT                          TYPE STRING VALUE 'ERDAT',
  ERZEIT                         TYPE STRING VALUE 'ERZEIT',
  MODDATE                        TYPE STRING VALUE 'MODDATE',
  MODTIME                        TYPE STRING VALUE 'MODTIME',
  MODNAM                         TYPE STRING VALUE 'MODNAM',
      END OF ZCDS_I_BKLOG_AREA,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZCDS_I_BKLOG_AREA,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '506B8D4A64A21EDD8BF2CB6D374F274F',
      END OF ZCDS_I_BKLOG_AREA,
    END OF SC_NODE_CATEGORY .
endinterface.
